### ISSUE TITLE
Automated Tfchain shop with bitcoin 

### ISSUE THREAD

**Issue by rkhamis** [threefoldtecharchive/jumpscaleX_archived#356]
A webpage where people can buy threefoldtokens with bitcoin 
preliminary spec:https://github.com/threefoldtech/rivine/blob/master/specs/webshop.md

**Comment by rkhamis** [comment]
➤ sabrinasadik commented:

* [ ] Check electrum  HD wallet + Define specs & possibilities ( https://github.com/threefoldtech/rivine/issues/470 ) @robvanmieghem: 6h 
 * [ ] Design for the token webshop using bitcoin ( https://github.com/threefoldfoundation/tfchain/issues/213 ) Roel
 * [ ] Implementation 42h
 * [ ]  Ability for the btc_electrum client to create a wallet using a Master Public Key ( https://github.com/threefoldtech/jumpscale_lib/issues/254 )

**Comment by rkhamis** [comment]
➤ Rob Van Mieghem commented:

Related but not part of this story( not required for launch):

* [ ] Check and document other bitcoin wallets compatible with electrum Master Public Key restore ( https://github.com/threefoldtech/rivine/issues/471 )

**Comment by rkhamis** [comment]
➤ xmonader commented:

DigitalMe application is a flask blueprint defines the APIs to serve staticfiles or communicate with gedis server via websockets using capnp messages.

Currently, Jumpscale team replacing the flask layer with lua and openresty ( https://openresty.org/en ) and adding support for json payloads with gedis server so it'll be more like JSONRPCServer ( https://json-rpc.readthedocs.io/en/latest/quickstart.html )

So the application would be 

* Frontend: defined in Lua/Openresty will be responsible for routing and static files
 * Backend: Gedis RPCServer (python)  will be responsbile application logic

**Comment by rkhamis** [comment]
➤ Rob Van Mieghem commented:

repository: https://github.com/threefoldfoundation/tftshop

**Comment by rkhamis** [comment]
➤ Rob Van Mieghem commented:

blocked until the digital me vue integration and rest api exposure is defined
