### ISSUE TITLE
As a user register (onboarding phase 1)

### ISSUE THREAD

**Issue by rkhamis** [threefoldtecharchive/jumpscaleX_archived#396]
* Ask email address
* Location where 3bot should be
* DoubleName of 3bot (needs to be unique, is 2x min 5 chars)
* We register name on the blockchain
* On email address we send location of 3bot ( $DoubleName.grid.tf) and some auth code at end 
* Once 3bot deployed.

This is done using a centralized BootStrap 3bot that provisions the 3bot on the chosen location

Todo : define recovery options in case of lost username/pass or totp key
Suggestion: create mechanism based on seed phrase

prerequisites:

* [ ] [digital me website concept and example ](https://github.com/threefoldtech/home/issues/132)

More information: 

https://github.com/threefoldfoundation/3bot/blob/master/specs/register.md
TODO:

* [ ] [Create a bootstrap 3bot flist ](https://github.com/threefoldfoundation/3bot/issues/4)
* [ ] [Create a user 3bot flist ](https://github.com/threefoldfoundation/3bot/issues/3)
* [ ] [Technical: Add Jimber to 3bot ](https://github.com/threefoldtech/home/issues/109)
* [ ] [Chat flow of bootstrap 3bot ](https://github.com/threefoldfoundation/3bot/issues/7) ( to be verified)
