### ISSUE TITLE
JSX_installer [development_installer]

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#515]
## goal

- the root cause of install issues has to do with the way how we do configuration mgmt in JSX
- see https://github.com/threefoldtech/jumpscaleX/pull/516 pullrequest

## todo

- [X] move sshagent functionality in installtools so can use there
- [X] move some of key loading to installtools
- [X] create MyEv.configure which makes it ONLY function to configure JSX
- [X] allow multiple SSH-Keys to be used
- [X] auto loading of ssh-keys
- [X] load ssh-agent if not loaded
- [X] use click for argument parsing in installer make all nice documentation
- [X] get better docker management in JSX cmdline
- [X] don't use 2 installers, go to one, now called JSX
- [x] rework NACL to not have to use redis
- [x] rework NACL to use new config management
- [ ] create a pyinstaller version of it and upload to releases (binary)
- [X] create config manager in  MyEnv.configure() 
- [X] put full blown config management in JSX tool for jumpscale call  MyEnv.configure() 
- [x] make sure that all config management is only done in this MyEnv.configure() method
- [ ] reuse parts of config towards docker, automatic push
- [ ] do import/export of configuration for kosmos (config classes), so we can do upgrades
- [ ] mount docker container to config on local filesystem (per container name) so we can re-use config when re-doing a docker container, so easier to develop with multiple containers
- [X] prepare support for sandbox on other location (WILL NOT BE TESTED, JUST PREPARED)
- [X] allow to work with multiple config directories on same computer  (WILL NOT BE TESTED, JUST PREPARED)
- [ ] update all installer doc to reflect the JSX tool (binary release)
- [X] kosmos or JSX both understand --configdir= ... to specify other config dir, all will work from that config file

## result

- this should resolve all bugs to do with restart container, secret for nacl, installer issues known today
- this should make it much more easy for user to get started with e.g. ssh-agent
- because of better arg parsing and easier structure should be easier to debug

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/58072003-9ec0de80-7b9e-11e9-87a6-97111eb2c17e.png)

**Comment by despiegk** [comment]
![Uploading image.png…]()

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/58072141-11ca5500-7b9f-11e9-9168-d947aee65520.png)

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/58072164-1db61700-7b9f-11e9-92b7-9b540375d4d7.png)

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/58072179-29094280-7b9f-11e9-81c3-ceeb6358eeb1.png)

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/58072261-68379380-7b9f-11e9-9574-ea1f05a60415.png)

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/58072274-784f7300-7b9f-11e9-82ec-eca0ceaf1b81.png)

**Comment by despiegk** [comment]
super old, no longer relevant
